import Head from "next/head";
import { Post } from "../components/Posts";
import { PostForm } from "../components/PostForm";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>My Post</h1>
        <ul className={styles.posts}>
          <li>
            <Post
              contents="at Function.getInitialProps loadGetInitialProps at renderToHTML"
              date="2021.08.01"
            />
          </li>
        </ul>
        <PostForm />
      </main>
    </div>
  );
}
