import Head from "next/head";
import { Post } from "../components/Posts";
import { PostForm } from "../components/PostForm";
import { Bio } from "../components/Bio";
import styles from "../styles/Home.module.scss";
import avatar from "../res/avatar.png";
import { useAuth } from "../hooks/useAuth";

export default function Home() {
  const { user, logIn } = useAuth();
  console.log("user", user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>
        <button onClick={logIn}>login</button>
      </p>
      <main className={styles.main}>
        <Bio
          handshot={avatar.src}
          name="JiYoon Lee"
          tagline="learning nextJS"
          role="frone-end"
        />
        <h1 className={styles.title}>My Post</h1>
        <ul className={styles.posts}>
          <li>
            <Post
              contents="at Function.getInitialProps loadGetInitialProps at renderToHTML"
              date="2021.08.01"
            />
          </li>
        </ul>
        <PostForm />
      </main>
    </div>
  );
}
