import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>My Post</h1>
        <ul className={styles.posts}>
          <li>
            <p className={styles.postsContent}>
              at Function.getInitialProps loadGetInitialProps at renderToHTML at
              async
            </p>
            <p className={styles.postsDate}>2021.08.01</p>
          </li>
          <li>
            <p className={styles.postsContent}>
              at Function.getInitialProps loadGetInitialProps at renderToHTML at
              async
            </p>
            <p className={styles.postsDate}>2021.08.01</p>
          </li>
          <li>
            <p className={styles.postsContent}>
              at Function.getInitialProps loadGetInitialProps at renderToHTML at
              async
            </p>
            <p className={styles.postsDate}>2021.08.01</p>
          </li>
        </ul>

        <form>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formButton}>Add New Post!</button>
        </form>
      </main>
    </div>
  );
}
